### ISSUE TITLE
Does not work for apk? 

### ISSUE THREAD

**Issue by thewayibyte** [sahad-mk/Fireprint#1]
I have one app that I tried to use with this script. 
I have this error: 
![image](https://github.com/sahad-mk/Fireprint/assets/6320442/36203637-fa7e-400f-a049-f33406d9375b)

The error says "Could not find the file path". This is how it looks within the folder: 
![image](https://github.com/sahad-mk/Fireprint/assets/6320442/0633d5ed-86e2-4352-ad80-82b3b40e0ddf)

If I use the apktool and "decompile" the app and go to: ../res/values/strings.xmls  I have this entry: 
![image](https://github.com/sahad-mk/Fireprint/assets/6320442/b1889c37-7239-489a-9f19-f7e08565c882)

So the question is: what I am doing wrong here ? :)

**Comment by sahad-mk** [comment]
Please provide the OS version
It seems like there's an issue with the directory path on the Windows OS. I'll check and revert

**Comment by sahad-mk** [comment]
**The issue has been resolved and the bug has been fixed. Closing this issue now.** 

`Please download the updated Fireprint tool and check. `

Please feel free to reopen if you encounter any further problems. Thanks!

**Comment by thewayibyte** [comment]
Sorry for my late answer. 
OS: Windows 10 Pro 22H2 (19045.4170).
Python 3.9.13

I have pulled the latest version and now it runs and looks like it hangs on " ←[37m Processing apk >←[0m ←[35;1m". 
After like 10 minutes in the folder "decomp" I see the correct folder with the name of the app and inside only one file "AndroidManifest.xml"

**Comment by sahad-mk** [comment]
The decompilation process takes time depending on the APK file size. 

Fireprint works fine for me on Windows 11. Could you please run the same scans on a different APK file and check? 

For this, you can download the vulnerable android app 'FireVu,' which can be found in the following GitHub repo:
**[FireVu](https://github.com/sahad-mk/FireVu)**

**Comment by thewayibyte** [comment]
I run it for around 45 min and nothing. I will try to run it on Windows 11.
